service: aws-python-flask-api

frameworkVersion: "3"

custom:
  wsgi:
    app: app.app 
  pythonRequirements:
    zip: true
    dockerizePip: non-linux
    invalidateCaches: true
    pythonBin: python3
    useDownloadCache: false
    useStaticCache: false

provider:
  name: aws
  runtime: python3.8

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

plugins:
  - serverless-wsgi
  - serverless-python-requirements
